name: BedHomes
main: org.jabelpeeps.bedhomes.BedHomes
version: ${project.version}
author: Jabelpeeps
softdepend: [Vault]

commands:
  home:
    description: Returns you to your Survival bed.
    usage: /bed