name: BedHomes
main: org.jabelpeeps.bedhomes.BedHomes
version: 1.0.0
author: Jabelpeeps
softdepend: [Vault]
api-version: 1.17

commands:
  bed:
    description: Returns you to your Survival bed.
    usage: /bed